---
ansible_ssh_host: "{{ inventory_hostname.split('.')[0] }}.a935.internal"
openshift_node_group_name: 'node-config-compute'
openshift_node_labels:
  - 'node-role.kubernetes.io/compute=true'

openshift_node_open_ports:
- service: "prometheus node exporter"
  port: "9100/tcp"    
...
