---
ansible_ssh_host: "{{ inventory_hostname.split('.')[0] }}.a935.internal"
openshift_hostname: "{{ ansible_ssh_host }}"
openshift_node_group_name: 'node-config-infra'
openshift_node_labels: 
  - 'node-role.kubernetes.io/infra=true'

openshift_node_open_ports:
- service: "router stats port"
  port: "1936/tcp"
- service: "prometheus node exporter"
  port: "9100/tcp"    
...
