---
openshift_node_group_name: 'node-config-master'
openshift_node_labels: 
  - 'node-role.kubernetes.io/master=true'

openshift_node_open_ports:
- service: "prometheus node exporter"
  port: "9100/tcp"    
...
